Privetes with prefix _
getninjas/javascript pull request #1
Opened 2017-04-03 22:28 UTC by MarcoBrunoBR

```javascript
    // bad
    this.__firstName__ = 'Panda';
    this.firstName = 'Panda';
    this.firstName_ = 'Panda';

    // good
    this._firstName = 'Panda';
```

2017-04-03 22:49 UTC, eduardojmatos commented
@MarcoBrunoBR então, concordo em usarmos `_` pra conceito de privado. E pra evitar o que está no comentário ali, podemos usar algumas ferramentas de coverage, pra garantir que os testes estão sendo feitos nesses métodos "privados".

2017-04-04 00:23 UTC, eduardojmatos requested changes

2017-04-04 00:23 UTC, eduardojmatos commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
@MarcoBrunoBR eu mudaria o texto, porque ainda dá a ideia de que private com _ é ruim.

Sugestão:

This convention is not bad at all. Tests must be done, even on the private methods. Tl; dr: if you want something "private", it is ok to use prefix `_`.

2017-04-04 16:04 UTC, wbotelhos commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
A descrição dos caras é exatamente o contrário do que deveria funcionar, o acordo de cavalheiros e boa fé, como qualquer coisa no mundo da programação.

> Mesmo não havendo um conceito de método privado, o `_` é uma forma de fechar um contrato de cavalheiros onde se convenciona que este método não é público e não seguirá as regras do Semantic Version. Ainda sim, este método é testado, para garantir uma granularidade e qualidade em todas as partes do teste.

2017-04-04 16:05 UTC, wbotelhos commented on README.md
> +    this.firstName = 'Panda';
Seria legal colocar uns `function() {}`, só para lembrar que, na maioria das vezes, vamos usar declaração de funções?

2017-04-04 16:05 UTC, wbotelhos approved these changes

2017-04-04 16:41 UTC, eduardojmatos commented on README.md
> +    this.firstName = 'Panda';
@wbotelhos justo. Quanto mais exemplos melhor ;)

2017-04-04 23:31 UTC, eduardojmatos commented
@iondrimba @GeorgeJegon podem olhar pra ver se concordam?

@MarcoBrunoBR o update que o @wbotelhos sugeriu faz sentido, consegue alterar?

2017-04-05 00:01 UTC, iondrimba commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
Eu concordo com o underscore prefix, acho um padrão já bem estabelecido. 
Sobre os testes de métodos privados, não sei se vale a pena testarmos eles diretamente.
Acho que testar o método "público" em que ele está sendo usado seria o suficiente.

2017-04-05 00:03 UTC, iondrimba commented on README.md
> +    this.firstName = 'Panda';
@wbotelhos @eduardojmatos Um exemplo com function seria bom mesmo 👍

2017-04-05 00:04 UTC, iondrimba requested changes
Adicionar exemplo com function privado

2017-04-05 00:13 UTC, eduardojmatos commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
@iondrimba concordo! Mas acho que teste nunca é demais, mesmo com os privados heheh (assunto pra outra hora)

2017-04-06 16:52 UTC, GeorgeJegon approved these changes
Só acertar os pontos que o pessoal levantou:
- exemplo com `function`

2017-04-06 17:42 UTC, wbotelhos commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
@iondrimba Ai fica uma discussão sobre fazer teste de modelo ou não, fazendo apenas de aceitação. #mamilos rs...

2017-04-10 20:01 UTC, MarcoBrunoBR commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
@wbotelhos só acho legal quando for dar sugestões de alteração do texto da documentação, já passar ele em inglês :-)
S2

2017-04-10 20:05 UTC, MarcoBrunoBR commented on README.md
> +    this.firstName = 'Panda';
@wbotelhos, @eduardojmatos e @iondrimba Done :-)

2017-04-10 20:25 UTC, MarcoBrunoBR commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
@wbotelhos alterado o texto :)

2017-04-10 20:26 UTC, iondrimba approved these changes

2017-04-10 20:37 UTC, wbotelhos commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
Eu not spike em englich, sory!

2017-04-10 20:38 UTC, wbotelhos approved these changes

2017-04-10 21:05 UTC, eduardojmatos approved these changes

2017-04-10 21:11 UTC, bsoares approved these changes

2017-04-10 21:23 UTC, Eliada commented on README.md
> +    > Why? JavaScript does not have the concept of privacy in terms of properties or methods. Although a leading underscore is a common convention to mean "private", in fact, these properties are ful
... if you want something to be "private", it should **be obvious that it is therefore use the `_`as a prefix**

2017-04-10 22:28 UTC, merged