Bye bye semicolon
getninjas/javascript pull request #2
Opened 2017-04-11 19:42 UTC by MarcoBrunoBR

Bye bye semicolon

2017-04-11 20:11 UTC, iondrimba requested changes
@MarcoBrunoBR já foi votado remover esse cara?

2017-04-11 20:36 UTC, GeorgeJegon approved these changes
:shipit:  não vejo problema em modificarmos esse padrão ai.

2017-04-11 20:42 UTC, dtamai approved these changes

2017-04-11 21:28 UTC, wbotelhos approved these changes

2017-04-15 19:33 UTC, restarac approved these changes

2017-04-15 19:33 UTC, restarac commented on README.md
> -  - [20.1](#20.1) **Yup.** eslint: [`semi`](http://eslint.org/docs/rules/semi.html) jscs: [`requireSemicolons`](http://jscs.info/rule/requireSemicolons)
Bem lembrado :)

2017-04-15 22:29 UTC, bsoares commented
Bizarro:
https://www.youtube.com/watch?v=Qlr-FGbhKaI

2017-04-17 12:32 UTC, iondrimba approved these changes

2017-04-17 13:37 UTC, merged

2017-04-17 15:02 UTC, eduardojmatos commented
@bsoares Os pontos deles são bons, mas vai exigir maturidade do time. Exemplos que temos que tomar cuidado:

http://benalman.com/news/2013/01/advice-javascript-semicolon-haters/

2017-04-17 15:05 UTC, eduardojmatos commented
Mais um só pra fechar meus pontos (tem muitos outros posts, mas os exemplos se resumem aos dos posts). https://brendaneich.com/2012/04/the-infernal-semicolon/